/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const folder = (name) => {
  /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig[string]} */
  const config = {
    type: 'category',
    label: name,
    collapsed: true,
    link: { type: 'generated-index' },
    items: [{ type: 'autogenerated', dirName: name }],
  }
  return config;
}

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  profession: [
    folder('计算机科学'),
    folder('C++'),
    folder('TypeScript'),
    folder('Julia'),
  ],
};

module.exports = sidebars;
