const folder = (name) => {
  /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig[string]} */
  const config = {
    type: 'category',
    label: name,
    collapsed: true,
    link: { type: 'generated-index', slug: `/${name}` },
    items: [{ type: 'autogenerated', dirName: name }],
  }
  return config;
}

const summary = (/** @type {string} */ name, /** @type {string[]} */ folders) => {
  /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig[string]} */
  const config = {
    type: 'category',
    label: name,
    link: { type: 'generated-index', slug: `/${name}` },
    items: folders.map(folder),
  };
  return config;
}

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  profession: [
    summary('专业素养', ['计算机科学', '软件工程', '数学']),
    summary('MIT 研究助理', ['高阶自动微分']),
  ],
  development: [
    summary('科学学习', ['知识输入', '知识内化']),
    summary('自我管理', ['时间管理', '目标管理']),
    summary('万物原理', ['艺术']),
  ],
  creation: [
    summary('影像', ['摄影光学', '图像信号处理', '视频信号处理', '视觉叙事']),
    summary('编码理论', ['汉字信息工程']),
  ]
};

module.exports = sidebars;
