const folder = (name) => {
  /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig[string]} */
  const config = {
    type: 'category',
    label: name,
    collapsed: true,
    link: { type: 'generated-index', slug: `/${name}` },
    items: [{ type: 'autogenerated', dirName: name }],
  }
  return config;
}

const summary = (/** @type {string} */ name, /** @type {string[]} */ folders) => {
  /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig[string]} */
  const config = {
    type: 'category',
    label: name,
    link: { type: 'generated-index', slug: `/${name}` },
    items: folders.map(folder),
  };
  return config;
}

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  profession: [
    summary('专业素养', ['计算机科学', '软件工程', '数学']),
    summary('MIT 研究助理', ['高阶自动微分']),
  ],
  development: [
    folder('科学学习'),
    folder('自我管理'),
  ],
  creation: [
    folder('影像'),
    folder('汉字信息工程'),
  ]
};

module.exports = sidebars;
