import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import { SidebarItemConfig } from "@docusaurus/plugin-content-docs/src/sidebars/types.js";

const folder = (name: string) => {
  const config: SidebarItemConfig = {
    type: "category",
    label: name,
    collapsed: true,
    link: { type: "generated-index", slug: `/${name}` },
    items: [{ type: "autogenerated", dirName: name }],
  };
  return config;
};

const summary = (name: string, folders: string[]) => {
  const config: SidebarItemConfig = {
    type: "category",
    label: name,
    link: { type: "generated-index", slug: `/${name}` },
    items: folders.map(folder),
  };
  return config;
};

const sidebars: SidebarsConfig = {
  profession: [folder("计算机科学"), folder("软件工程"), folder("数学")],
  development: [folder("科学学习"), folder("自我管理")],
  creation: [folder("影像"), folder("汉字信息工程")],
};

export default sidebars;
